# Generated by Django 5.0.9 on 2025-01-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project_milestone',
            fields=[
                ('org_pid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
            ],
            options={
                'db_table': 'pm_org_schemes_location_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='project_milestone_apps_open',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('Application_Open_Count', models.IntegerField()),
                ('created_date', models.DateField()),
            ],
            options={
                'db_table': 'daily_aggregates',
                'managed': False,
            },
        ),
    ]
