# Generated by Django 4.2.19 on 2025-02-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project_summary',
            fields=[
                ('project_name', models.CharField(max_length=100)),
                ('scheme_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('project_status', models.CharField(max_length=100)),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('org_pid', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pm_org_schemes_locations_mapping',
            },
        ),
    ]
