# Generated by Django 5.0.9 on 2025-01-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_summary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_summary',
            name='id',
        ),
        migrations.RemoveField(
            model_name='project_summary',
            name='pid',
        ),
        migrations.AddField(
            model_name='project_summary',
            name='org_pid',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
