# Generated by Django 4.2.19 on 2025-02-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project_kpi',
            fields=[
                ('project_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('Application_Open_Count', models.IntegerField()),
                ('Docket_Submitted_Count', models.IntegerField()),
                ('Benefit_Received_Count', models.IntegerField()),
                ('scheme_value', models.IntegerField()),
                ('scheme_name', models.CharField(max_length=100)),
                ('project_names', models.CharField(max_length=100)),
                ('citizen_state', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'daily_aggregates',
            },
        ),
    ]
