# Generated by Django 5.0.9 on 2025-01-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('application_open_count', models.IntegerField()),
            ],
            options={
                'db_table': 'daily_aggregates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='project_kpi',
            fields=[
                ('project_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('Application_Open_Count', models.IntegerField()),
                ('Docket_Submitted_Count', models.IntegerField()),
                ('Benefit_Received_Count', models.IntegerField()),
                ('scheme_value', models.IntegerField()),
            ],
            options={
                'db_table': 'daily_aggregates',
                'managed': False,
            },
        ),
    ]
